diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: "wheel_left_joint"
  right_wheel: "wheel_right_joint"
  publish_rate: 50

  wheel_separation: 0.160
  wheel_radius: 0.033

  cmd_vel_timeout: 0.25
  base_frame_id: "base_footprint"
  odom_frame_id: "odom"
  enable_odom_tf: true

  pose_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]

  linear:
    x:
      has_velocity_limits: true
      max_velocity: 0.22
      min_velocity: -0.22
      has_acceleration_limits: true
      max_acceleration: 2.5

  angular:
    z:
      has_velocity_limits: true
      max_velocity: 2.84
      has_acceleration_limits: true
      max_acceleration: 3.2

gazebo_ros_control:
  pid_gains:
    wheel_left_joint:
      p: 10.0
      i: 0.0
      d: 0.0
    wheel_right_joint:
      p: 10.0
      i: 0.0
      d: 0.0
