#!/usr/bin/env python3
#!/usr/bin/env python3
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../src'))

from pathfinding_simulation.path_follower_node import main

if __name__ == "__main__":
    main()
